/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

/* oxlint-disable */

/* oxfmt-ignore */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as AppRouteRouteImport } from "./routes/app/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AppTimesheetRouteImport } from "./routes/app/timesheet";
import { Route as AppTimerRouteImport } from "./routes/app/timer";
import { Route as AppReportsRouteImport } from "./routes/app/reports";
import { Route as AppProfileRouteImport } from "./routes/app/profile";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRouteRoute = AppRouteRouteImport.update({
  id: "/app",
  path: "/app",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AppTimesheetRoute = AppTimesheetRouteImport.update({
  id: "/timesheet",
  path: "/timesheet",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppTimerRoute = AppTimerRouteImport.update({
  id: "/timer",
  path: "/timer",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppReportsRoute = AppReportsRouteImport.update({
  id: "/reports",
  path: "/reports",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppProfileRoute = AppProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => AppRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/app": typeof AppRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/app/profile": typeof AppProfileRoute;
  "/app/reports": typeof AppReportsRoute;
  "/app/timer": typeof AppTimerRoute;
  "/app/timesheet": typeof AppTimesheetRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/app": typeof AppRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/app/profile": typeof AppProfileRoute;
  "/app/reports": typeof AppReportsRoute;
  "/app/timer": typeof AppTimerRoute;
  "/app/timesheet": typeof AppTimesheetRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/app": typeof AppRouteRouteWithChildren;
  "/login": typeof LoginRoute;
  "/app/profile": typeof AppProfileRoute;
  "/app/reports": typeof AppReportsRoute;
  "/app/timer": typeof AppTimerRoute;
  "/app/timesheet": typeof AppTimesheetRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/app"
    | "/login"
    | "/app/profile"
    | "/app/reports"
    | "/app/timer"
    | "/app/timesheet";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/app"
    | "/login"
    | "/app/profile"
    | "/app/reports"
    | "/app/timer"
    | "/app/timesheet";
  id:
    | "__root__"
    | "/"
    | "/app"
    | "/login"
    | "/app/profile"
    | "/app/reports"
    | "/app/timer"
    | "/app/timesheet";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRouteRoute: typeof AppRouteRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app": {
      id: "/app";
      path: "/app";
      fullPath: "/app";
      preLoaderRoute: typeof AppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/app/timesheet": {
      id: "/app/timesheet";
      path: "/timesheet";
      fullPath: "/app/timesheet";
      preLoaderRoute: typeof AppTimesheetRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/timer": {
      id: "/app/timer";
      path: "/timer";
      fullPath: "/app/timer";
      preLoaderRoute: typeof AppTimerRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/reports": {
      id: "/app/reports";
      path: "/reports";
      fullPath: "/app/reports";
      preLoaderRoute: typeof AppReportsRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/app/profile": {
      id: "/app/profile";
      path: "/profile";
      fullPath: "/app/profile";
      preLoaderRoute: typeof AppProfileRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
  }
}

interface AppRouteRouteChildren {
  AppProfileRoute: typeof AppProfileRoute;
  AppReportsRoute: typeof AppReportsRoute;
  AppTimerRoute: typeof AppTimerRoute;
  AppTimesheetRoute: typeof AppTimesheetRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppTimerRoute: AppTimerRoute,
  AppTimesheetRoute: AppTimesheetRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
