/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

/* oxlint-disable */

/* oxfmt-ignore */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VerifyEmailRouteImport } from "./routes/verify-email";
import { Route as SignUpRouteImport } from "./routes/sign-up";
import { Route as ResetPasswordRouteImport } from "./routes/reset-password";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as OrganizationInvitationsRouteImport } from "./routes/organization-invitations";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as CreateOrganizationRouteImport } from "./routes/create-organization";
import { Route as AccessDeniedRouteImport } from "./routes/access-denied";
import { Route as OrgSlugRouteRouteImport } from "./routes/$orgSlug/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OrgSlugIndexRouteImport } from "./routes/$orgSlug/index";
import { Route as OrgSlugDashboardRouteImport } from "./routes/$orgSlug/dashboard";
import { Route as OrgSlugTimesheetIndexRouteImport } from "./routes/$orgSlug/timesheet/index";
import { Route as OrgSlugSettingsIndexRouteImport } from "./routes/$orgSlug/settings/index";
import { Route as OrgSlugProjectsIndexRouteImport } from "./routes/$orgSlug/projects/index";
import { Route as OrgSlugMembersIndexRouteImport } from "./routes/$orgSlug/members/index";
import { Route as OrgSlugClientsIndexRouteImport } from "./routes/$orgSlug/clients/index";
import { Route as OrgSlugProjectsProjectIdIndexRouteImport } from "./routes/$orgSlug/projects/$projectId/index";

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any);
const SignUpRoute = SignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const OrganizationInvitationsRoute = OrganizationInvitationsRouteImport.update({
  id: "/organization-invitations",
  path: "/organization-invitations",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: "/create-organization",
  path: "/create-organization",
  getParentRoute: () => rootRouteImport,
} as any);
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: "/access-denied",
  path: "/access-denied",
  getParentRoute: () => rootRouteImport,
} as any);
const OrgSlugRouteRoute = OrgSlugRouteRouteImport.update({
  id: "/$orgSlug",
  path: "/$orgSlug",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OrgSlugIndexRoute = OrgSlugIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OrgSlugRouteRoute,
} as any);
const OrgSlugDashboardRoute = OrgSlugDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => OrgSlugRouteRoute,
} as any);
const OrgSlugTimesheetIndexRoute = OrgSlugTimesheetIndexRouteImport.update({
  id: "/timesheet/",
  path: "/timesheet/",
  getParentRoute: () => OrgSlugRouteRoute,
} as any);
const OrgSlugSettingsIndexRoute = OrgSlugSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => OrgSlugRouteRoute,
} as any);
const OrgSlugProjectsIndexRoute = OrgSlugProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => OrgSlugRouteRoute,
} as any);
const OrgSlugMembersIndexRoute = OrgSlugMembersIndexRouteImport.update({
  id: "/members/",
  path: "/members/",
  getParentRoute: () => OrgSlugRouteRoute,
} as any);
const OrgSlugClientsIndexRoute = OrgSlugClientsIndexRouteImport.update({
  id: "/clients/",
  path: "/clients/",
  getParentRoute: () => OrgSlugRouteRoute,
} as any);
const OrgSlugProjectsProjectIdIndexRoute =
  OrgSlugProjectsProjectIdIndexRouteImport.update({
    id: "/projects/$projectId/",
    path: "/projects/$projectId/",
    getParentRoute: () => OrgSlugRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$orgSlug": typeof OrgSlugRouteRouteWithChildren;
  "/access-denied": typeof AccessDeniedRoute;
  "/create-organization": typeof CreateOrganizationRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/login": typeof LoginRoute;
  "/organization-invitations": typeof OrganizationInvitationsRoute;
  "/profile": typeof ProfileRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/sign-up": typeof SignUpRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/$orgSlug/dashboard": typeof OrgSlugDashboardRoute;
  "/$orgSlug/": typeof OrgSlugIndexRoute;
  "/$orgSlug/clients/": typeof OrgSlugClientsIndexRoute;
  "/$orgSlug/members/": typeof OrgSlugMembersIndexRoute;
  "/$orgSlug/projects/": typeof OrgSlugProjectsIndexRoute;
  "/$orgSlug/settings/": typeof OrgSlugSettingsIndexRoute;
  "/$orgSlug/timesheet/": typeof OrgSlugTimesheetIndexRoute;
  "/$orgSlug/projects/$projectId/": typeof OrgSlugProjectsProjectIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/access-denied": typeof AccessDeniedRoute;
  "/create-organization": typeof CreateOrganizationRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/login": typeof LoginRoute;
  "/organization-invitations": typeof OrganizationInvitationsRoute;
  "/profile": typeof ProfileRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/sign-up": typeof SignUpRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/$orgSlug/dashboard": typeof OrgSlugDashboardRoute;
  "/$orgSlug": typeof OrgSlugIndexRoute;
  "/$orgSlug/clients": typeof OrgSlugClientsIndexRoute;
  "/$orgSlug/members": typeof OrgSlugMembersIndexRoute;
  "/$orgSlug/projects": typeof OrgSlugProjectsIndexRoute;
  "/$orgSlug/settings": typeof OrgSlugSettingsIndexRoute;
  "/$orgSlug/timesheet": typeof OrgSlugTimesheetIndexRoute;
  "/$orgSlug/projects/$projectId": typeof OrgSlugProjectsProjectIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$orgSlug": typeof OrgSlugRouteRouteWithChildren;
  "/access-denied": typeof AccessDeniedRoute;
  "/create-organization": typeof CreateOrganizationRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/login": typeof LoginRoute;
  "/organization-invitations": typeof OrganizationInvitationsRoute;
  "/profile": typeof ProfileRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/sign-up": typeof SignUpRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/$orgSlug/dashboard": typeof OrgSlugDashboardRoute;
  "/$orgSlug/": typeof OrgSlugIndexRoute;
  "/$orgSlug/clients/": typeof OrgSlugClientsIndexRoute;
  "/$orgSlug/members/": typeof OrgSlugMembersIndexRoute;
  "/$orgSlug/projects/": typeof OrgSlugProjectsIndexRoute;
  "/$orgSlug/settings/": typeof OrgSlugSettingsIndexRoute;
  "/$orgSlug/timesheet/": typeof OrgSlugTimesheetIndexRoute;
  "/$orgSlug/projects/$projectId/": typeof OrgSlugProjectsProjectIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$orgSlug"
    | "/access-denied"
    | "/create-organization"
    | "/forgot-password"
    | "/login"
    | "/organization-invitations"
    | "/profile"
    | "/reset-password"
    | "/sign-up"
    | "/verify-email"
    | "/$orgSlug/dashboard"
    | "/$orgSlug/"
    | "/$orgSlug/clients/"
    | "/$orgSlug/members/"
    | "/$orgSlug/projects/"
    | "/$orgSlug/settings/"
    | "/$orgSlug/timesheet/"
    | "/$orgSlug/projects/$projectId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/access-denied"
    | "/create-organization"
    | "/forgot-password"
    | "/login"
    | "/organization-invitations"
    | "/profile"
    | "/reset-password"
    | "/sign-up"
    | "/verify-email"
    | "/$orgSlug/dashboard"
    | "/$orgSlug"
    | "/$orgSlug/clients"
    | "/$orgSlug/members"
    | "/$orgSlug/projects"
    | "/$orgSlug/settings"
    | "/$orgSlug/timesheet"
    | "/$orgSlug/projects/$projectId";
  id:
    | "__root__"
    | "/"
    | "/$orgSlug"
    | "/access-denied"
    | "/create-organization"
    | "/forgot-password"
    | "/login"
    | "/organization-invitations"
    | "/profile"
    | "/reset-password"
    | "/sign-up"
    | "/verify-email"
    | "/$orgSlug/dashboard"
    | "/$orgSlug/"
    | "/$orgSlug/clients/"
    | "/$orgSlug/members/"
    | "/$orgSlug/projects/"
    | "/$orgSlug/settings/"
    | "/$orgSlug/timesheet/"
    | "/$orgSlug/projects/$projectId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  OrgSlugRouteRoute: typeof OrgSlugRouteRouteWithChildren;
  AccessDeniedRoute: typeof AccessDeniedRoute;
  CreateOrganizationRoute: typeof CreateOrganizationRoute;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  OrganizationInvitationsRoute: typeof OrganizationInvitationsRoute;
  ProfileRoute: typeof ProfileRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  SignUpRoute: typeof SignUpRoute;
  VerifyEmailRoute: typeof VerifyEmailRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email";
      path: "/verify-email";
      fullPath: "/verify-email";
      preLoaderRoute: typeof VerifyEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-up": {
      id: "/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof SignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reset-password": {
      id: "/reset-password";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/organization-invitations": {
      id: "/organization-invitations";
      path: "/organization-invitations";
      fullPath: "/organization-invitations";
      preLoaderRoute: typeof OrganizationInvitationsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forgot-password": {
      id: "/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/create-organization": {
      id: "/create-organization";
      path: "/create-organization";
      fullPath: "/create-organization";
      preLoaderRoute: typeof CreateOrganizationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/access-denied": {
      id: "/access-denied";
      path: "/access-denied";
      fullPath: "/access-denied";
      preLoaderRoute: typeof AccessDeniedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$orgSlug": {
      id: "/$orgSlug";
      path: "/$orgSlug";
      fullPath: "/$orgSlug";
      preLoaderRoute: typeof OrgSlugRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$orgSlug/": {
      id: "/$orgSlug/";
      path: "/";
      fullPath: "/$orgSlug/";
      preLoaderRoute: typeof OrgSlugIndexRouteImport;
      parentRoute: typeof OrgSlugRouteRoute;
    };
    "/$orgSlug/dashboard": {
      id: "/$orgSlug/dashboard";
      path: "/dashboard";
      fullPath: "/$orgSlug/dashboard";
      preLoaderRoute: typeof OrgSlugDashboardRouteImport;
      parentRoute: typeof OrgSlugRouteRoute;
    };
    "/$orgSlug/timesheet/": {
      id: "/$orgSlug/timesheet/";
      path: "/timesheet";
      fullPath: "/$orgSlug/timesheet/";
      preLoaderRoute: typeof OrgSlugTimesheetIndexRouteImport;
      parentRoute: typeof OrgSlugRouteRoute;
    };
    "/$orgSlug/settings/": {
      id: "/$orgSlug/settings/";
      path: "/settings";
      fullPath: "/$orgSlug/settings/";
      preLoaderRoute: typeof OrgSlugSettingsIndexRouteImport;
      parentRoute: typeof OrgSlugRouteRoute;
    };
    "/$orgSlug/projects/": {
      id: "/$orgSlug/projects/";
      path: "/projects";
      fullPath: "/$orgSlug/projects/";
      preLoaderRoute: typeof OrgSlugProjectsIndexRouteImport;
      parentRoute: typeof OrgSlugRouteRoute;
    };
    "/$orgSlug/members/": {
      id: "/$orgSlug/members/";
      path: "/members";
      fullPath: "/$orgSlug/members/";
      preLoaderRoute: typeof OrgSlugMembersIndexRouteImport;
      parentRoute: typeof OrgSlugRouteRoute;
    };
    "/$orgSlug/clients/": {
      id: "/$orgSlug/clients/";
      path: "/clients";
      fullPath: "/$orgSlug/clients/";
      preLoaderRoute: typeof OrgSlugClientsIndexRouteImport;
      parentRoute: typeof OrgSlugRouteRoute;
    };
    "/$orgSlug/projects/$projectId/": {
      id: "/$orgSlug/projects/$projectId/";
      path: "/projects/$projectId";
      fullPath: "/$orgSlug/projects/$projectId/";
      preLoaderRoute: typeof OrgSlugProjectsProjectIdIndexRouteImport;
      parentRoute: typeof OrgSlugRouteRoute;
    };
  }
}

interface OrgSlugRouteRouteChildren {
  OrgSlugDashboardRoute: typeof OrgSlugDashboardRoute;
  OrgSlugIndexRoute: typeof OrgSlugIndexRoute;
  OrgSlugClientsIndexRoute: typeof OrgSlugClientsIndexRoute;
  OrgSlugMembersIndexRoute: typeof OrgSlugMembersIndexRoute;
  OrgSlugProjectsIndexRoute: typeof OrgSlugProjectsIndexRoute;
  OrgSlugSettingsIndexRoute: typeof OrgSlugSettingsIndexRoute;
  OrgSlugTimesheetIndexRoute: typeof OrgSlugTimesheetIndexRoute;
  OrgSlugProjectsProjectIdIndexRoute: typeof OrgSlugProjectsProjectIdIndexRoute;
}

const OrgSlugRouteRouteChildren: OrgSlugRouteRouteChildren = {
  OrgSlugDashboardRoute: OrgSlugDashboardRoute,
  OrgSlugIndexRoute: OrgSlugIndexRoute,
  OrgSlugClientsIndexRoute: OrgSlugClientsIndexRoute,
  OrgSlugMembersIndexRoute: OrgSlugMembersIndexRoute,
  OrgSlugProjectsIndexRoute: OrgSlugProjectsIndexRoute,
  OrgSlugSettingsIndexRoute: OrgSlugSettingsIndexRoute,
  OrgSlugTimesheetIndexRoute: OrgSlugTimesheetIndexRoute,
  OrgSlugProjectsProjectIdIndexRoute: OrgSlugProjectsProjectIdIndexRoute,
};

const OrgSlugRouteRouteWithChildren = OrgSlugRouteRoute._addFileChildren(
  OrgSlugRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRouteRoute: OrgSlugRouteRouteWithChildren,
  AccessDeniedRoute: AccessDeniedRoute,
  CreateOrganizationRoute: CreateOrganizationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OrganizationInvitationsRoute: OrganizationInvitationsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
