/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as VerifyEmailRouteImport } from "./routes/verify-email";
import { Route as SignUpRouteImport } from "./routes/sign-up";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as ForgotPasswordRouteImport } from "./routes/forgot-password";
import { Route as OrgIdRouteRouteImport } from "./routes/$orgId/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as OrgIdIndexRouteImport } from "./routes/$orgId/index";
import { Route as OrgIdTimesheetIndexRouteImport } from "./routes/$orgId/timesheet/index";
import { Route as OrgIdSettingsIndexRouteImport } from "./routes/$orgId/settings/index";
import { Route as OrgIdProjectsIndexRouteImport } from "./routes/$orgId/projects/index";
import { Route as OrgIdMembersIndexRouteImport } from "./routes/$orgId/members/index";
import { Route as OrgIdClientsIndexRouteImport } from "./routes/$orgId/clients/index";
import { Route as OrgIdProjectsProjectIdIndexRouteImport } from "./routes/$orgId/projects/$projectId/index";

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any);
const SignUpRoute = SignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => rootRouteImport,
} as any);
const OrgIdRouteRoute = OrgIdRouteRouteImport.update({
  id: "/$orgId",
  path: "/$orgId",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const OrgIdIndexRoute = OrgIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => OrgIdRouteRoute,
} as any);
const OrgIdTimesheetIndexRoute = OrgIdTimesheetIndexRouteImport.update({
  id: "/timesheet/",
  path: "/timesheet/",
  getParentRoute: () => OrgIdRouteRoute,
} as any);
const OrgIdSettingsIndexRoute = OrgIdSettingsIndexRouteImport.update({
  id: "/settings/",
  path: "/settings/",
  getParentRoute: () => OrgIdRouteRoute,
} as any);
const OrgIdProjectsIndexRoute = OrgIdProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => OrgIdRouteRoute,
} as any);
const OrgIdMembersIndexRoute = OrgIdMembersIndexRouteImport.update({
  id: "/members/",
  path: "/members/",
  getParentRoute: () => OrgIdRouteRoute,
} as any);
const OrgIdClientsIndexRoute = OrgIdClientsIndexRouteImport.update({
  id: "/clients/",
  path: "/clients/",
  getParentRoute: () => OrgIdRouteRoute,
} as any);
const OrgIdProjectsProjectIdIndexRoute =
  OrgIdProjectsProjectIdIndexRouteImport.update({
    id: "/projects/$projectId/",
    path: "/projects/$projectId/",
    getParentRoute: () => OrgIdRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/$orgId": typeof OrgIdRouteRouteWithChildren;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/login": typeof LoginRoute;
  "/sign-up": typeof SignUpRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/$orgId/": typeof OrgIdIndexRoute;
  "/$orgId/clients/": typeof OrgIdClientsIndexRoute;
  "/$orgId/members/": typeof OrgIdMembersIndexRoute;
  "/$orgId/projects/": typeof OrgIdProjectsIndexRoute;
  "/$orgId/settings/": typeof OrgIdSettingsIndexRoute;
  "/$orgId/timesheet/": typeof OrgIdTimesheetIndexRoute;
  "/$orgId/projects/$projectId/": typeof OrgIdProjectsProjectIdIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/login": typeof LoginRoute;
  "/sign-up": typeof SignUpRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/$orgId": typeof OrgIdIndexRoute;
  "/$orgId/clients": typeof OrgIdClientsIndexRoute;
  "/$orgId/members": typeof OrgIdMembersIndexRoute;
  "/$orgId/projects": typeof OrgIdProjectsIndexRoute;
  "/$orgId/settings": typeof OrgIdSettingsIndexRoute;
  "/$orgId/timesheet": typeof OrgIdTimesheetIndexRoute;
  "/$orgId/projects/$projectId": typeof OrgIdProjectsProjectIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/$orgId": typeof OrgIdRouteRouteWithChildren;
  "/forgot-password": typeof ForgotPasswordRoute;
  "/login": typeof LoginRoute;
  "/sign-up": typeof SignUpRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/$orgId/": typeof OrgIdIndexRoute;
  "/$orgId/clients/": typeof OrgIdClientsIndexRoute;
  "/$orgId/members/": typeof OrgIdMembersIndexRoute;
  "/$orgId/projects/": typeof OrgIdProjectsIndexRoute;
  "/$orgId/settings/": typeof OrgIdSettingsIndexRoute;
  "/$orgId/timesheet/": typeof OrgIdTimesheetIndexRoute;
  "/$orgId/projects/$projectId/": typeof OrgIdProjectsProjectIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/$orgId"
    | "/forgot-password"
    | "/login"
    | "/sign-up"
    | "/verify-email"
    | "/$orgId/"
    | "/$orgId/clients/"
    | "/$orgId/members/"
    | "/$orgId/projects/"
    | "/$orgId/settings/"
    | "/$orgId/timesheet/"
    | "/$orgId/projects/$projectId/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/forgot-password"
    | "/login"
    | "/sign-up"
    | "/verify-email"
    | "/$orgId"
    | "/$orgId/clients"
    | "/$orgId/members"
    | "/$orgId/projects"
    | "/$orgId/settings"
    | "/$orgId/timesheet"
    | "/$orgId/projects/$projectId";
  id:
    | "__root__"
    | "/"
    | "/$orgId"
    | "/forgot-password"
    | "/login"
    | "/sign-up"
    | "/verify-email"
    | "/$orgId/"
    | "/$orgId/clients/"
    | "/$orgId/members/"
    | "/$orgId/projects/"
    | "/$orgId/settings/"
    | "/$orgId/timesheet/"
    | "/$orgId/projects/$projectId/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  OrgIdRouteRoute: typeof OrgIdRouteRouteWithChildren;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  SignUpRoute: typeof SignUpRoute;
  VerifyEmailRoute: typeof VerifyEmailRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email";
      path: "/verify-email";
      fullPath: "/verify-email";
      preLoaderRoute: typeof VerifyEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-up": {
      id: "/sign-up";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof SignUpRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/forgot-password": {
      id: "/forgot-password";
      path: "/forgot-password";
      fullPath: "/forgot-password";
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$orgId": {
      id: "/$orgId";
      path: "/$orgId";
      fullPath: "/$orgId";
      preLoaderRoute: typeof OrgIdRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/$orgId/": {
      id: "/$orgId/";
      path: "/";
      fullPath: "/$orgId/";
      preLoaderRoute: typeof OrgIdIndexRouteImport;
      parentRoute: typeof OrgIdRouteRoute;
    };
    "/$orgId/timesheet/": {
      id: "/$orgId/timesheet/";
      path: "/timesheet";
      fullPath: "/$orgId/timesheet/";
      preLoaderRoute: typeof OrgIdTimesheetIndexRouteImport;
      parentRoute: typeof OrgIdRouteRoute;
    };
    "/$orgId/settings/": {
      id: "/$orgId/settings/";
      path: "/settings";
      fullPath: "/$orgId/settings/";
      preLoaderRoute: typeof OrgIdSettingsIndexRouteImport;
      parentRoute: typeof OrgIdRouteRoute;
    };
    "/$orgId/projects/": {
      id: "/$orgId/projects/";
      path: "/projects";
      fullPath: "/$orgId/projects/";
      preLoaderRoute: typeof OrgIdProjectsIndexRouteImport;
      parentRoute: typeof OrgIdRouteRoute;
    };
    "/$orgId/members/": {
      id: "/$orgId/members/";
      path: "/members";
      fullPath: "/$orgId/members/";
      preLoaderRoute: typeof OrgIdMembersIndexRouteImport;
      parentRoute: typeof OrgIdRouteRoute;
    };
    "/$orgId/clients/": {
      id: "/$orgId/clients/";
      path: "/clients";
      fullPath: "/$orgId/clients/";
      preLoaderRoute: typeof OrgIdClientsIndexRouteImport;
      parentRoute: typeof OrgIdRouteRoute;
    };
    "/$orgId/projects/$projectId/": {
      id: "/$orgId/projects/$projectId/";
      path: "/projects/$projectId";
      fullPath: "/$orgId/projects/$projectId/";
      preLoaderRoute: typeof OrgIdProjectsProjectIdIndexRouteImport;
      parentRoute: typeof OrgIdRouteRoute;
    };
  }
}

interface OrgIdRouteRouteChildren {
  OrgIdIndexRoute: typeof OrgIdIndexRoute;
  OrgIdClientsIndexRoute: typeof OrgIdClientsIndexRoute;
  OrgIdMembersIndexRoute: typeof OrgIdMembersIndexRoute;
  OrgIdProjectsIndexRoute: typeof OrgIdProjectsIndexRoute;
  OrgIdSettingsIndexRoute: typeof OrgIdSettingsIndexRoute;
  OrgIdTimesheetIndexRoute: typeof OrgIdTimesheetIndexRoute;
  OrgIdProjectsProjectIdIndexRoute: typeof OrgIdProjectsProjectIdIndexRoute;
}

const OrgIdRouteRouteChildren: OrgIdRouteRouteChildren = {
  OrgIdIndexRoute: OrgIdIndexRoute,
  OrgIdClientsIndexRoute: OrgIdClientsIndexRoute,
  OrgIdMembersIndexRoute: OrgIdMembersIndexRoute,
  OrgIdProjectsIndexRoute: OrgIdProjectsIndexRoute,
  OrgIdSettingsIndexRoute: OrgIdSettingsIndexRoute,
  OrgIdTimesheetIndexRoute: OrgIdTimesheetIndexRoute,
  OrgIdProjectsProjectIdIndexRoute: OrgIdProjectsProjectIdIndexRoute,
};

const OrgIdRouteRouteWithChildren = OrgIdRouteRoute._addFileChildren(
  OrgIdRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgIdRouteRoute: OrgIdRouteRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  SignUpRoute: SignUpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
